### ISSUE TITLE
Version of libskia.so

### ISSUE THREAD

**Issue by kotovaleksandr** [gman4455/Goelze.SkiaSharp.NativeAssets.AlpineLinux#1]
Hi! Thanks for alpine package. Whats version of libskia.so your use? libskia.so needed for applications using SkiaSharp?
I'm trying use simple application with Avalonia on Alpine (https://github.com/AvaloniaUI/Avalonia/issues/2464) with your package, but does not work - don't throw errors, but generate empty image.

**Comment by goelze** [comment]
I tested the package on Alpine 3.9 on docker, and I used an empty project with the SkiaSharp package (v1.68.0) and this package (v1.68.0). You also need to have `fontconfig` installed on your machine
